### ISSUE TITLE
how to read django saved data in redis from golang

### ISSUE THREAD

**Issue by wangbl11** [nlpodyssey/gopickle#14]
my django project put data(maybe set or dict) in redis, then I want to read out in golang.
could y pls give me a detailed example.

**Comment by sbinet** [comment]
from the `README`:

```go
import "github.com/nlpodyssey/gopickle/pickle"

// ...

// from file
foo, err := pickle.Load("foo.p") 

// from string
stringDump := "I42\n."
bar, err := pickle.Loads(stringDump)

// ...
```

so, just read the data from Redis into a `[]byte`, `string` or `os.File` and `pickle.Load` it (or `pickle.Loads` it).

**Comment by sbinet** [comment]
(closing. feel free to reopen if that wasn't too helpful)
