### ISSUE TITLE
More features

### ISSUE THREAD

**Issue by aivaki** [nlpodyssey/gopickle#7]
> ### PyTorch
> 
> The library currently provides a high-level function for loading a module file:
> 
> ```go
> import "github.com/nlpodyssey/gopickle/pytorch"
> 
> // ...
> 
> myModel, err := pytorch.Load("module.pt")
> 
> // ...
> ```
> 
> More features will be provided in the future.

Will work on this project continue? We have tried working with models using all known packages, but they are useless. Mainly for the reasons that they have not been updated for a long time or do not implement all the necessary methods. Our team considers your solution very promising, and we are even ready to contribute to it.

**Comment by matteo-grella** [comment]
> Our team considers your solution very promising, and we are even ready to contribute to it.

This is fantastic, @aivaki!

Please feel free to discuss your possible contributions and submit your PRs!
